### ISSUE TITLE
Just "topics" and "description"

### ISSUE THREAD

**Issue by mmazanec22** [codeforamerica/brigade-project-index-statusboard#10] opened 2020-03-30 23:31 UTC
Currently underneath a project description that has topics and a description it says "[checkmark] Github Topics  [checkmark] Github Description".  However the statusboard is flexible and magical and allows for not-github-based projects to be included.  It would perhaps therefore make sense to change this language.

**Comment by mmazanec22** [comment] 2020-03-30 23:38
Maybe the /topics/:topic page would be an appropriate place to include a link to the corresponding tag on Discourse (https://discourse.codeforamerica.org/tag/:topic)?  And a project's metadata could include a field for a Discourse wiki and the display would show that link if it existed, and a link to the relevant tags on Discourse if it didn't?

**Comment by nikolajbaer** [comment] 2020-04-01 16:21
Thanks Melanie, this is a duplicate of #9 , so I am going to close this, and reference your ideas on the other issue.

@themightychris also added helpful notes on pulling from the Discourse API to provide better linking

**Closed by nikolajbaer** 2020-04-01 16:21 UTC
